// <auto-generated />
namespace TechShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class createstor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createstor));
        
        string IMigrationMetadata.Id
        {
            get { return "202003251448363_create-stor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
